name: Angular Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  code-quality-frontend: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npx nx run frontend:lint
  service-tests: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npx nx test frontend --parallel --maxParallel=4


- name: DigitalOcean Docker Image Publish
  uses: ripplr-io/docr-docker-publish@v1
  with:
    # rename this path
    image_path: registry-path/image-path
    # Example when you have a non-default dockerfile
    dockerfile: ./docker/dev.Dockerfile